<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/11/26 02:59:58
sfConfig::add(array(
  'app_tmcTwitterBootstrapPlugin_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap.min.css',
  'app_tmcTwitterBootstrapPlugin_responsive_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap-responsive.min.css',
  'app_tmcTwitterBootstrapPlugin_admin_styles_path' => '/tmcTwitterBootstrapPlugin/css/styles.css',
  'app_tmcTwitterBootstrapPlugin_jquery_path' => '/tmcTwitterBootstrapPlugin/js/jquery.min.js',
  'app_tmcTwitterBootstrapPlugin_bootstrap_js_path' => '/tmcTwitterBootstrapPlugin/js/bootstrap.min.js',
  'app_tmcTwitterBootstrapPlugin_admin_js_path' => '/tmcTwitterBootstrapPlugin/js/global.js',
));
