<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/11/09 14:37:59
sfConfig::add(array(
  'mod_public_enabled' => true,
  'mod_public_view_class' => 'sfPHP',
  'mod_public_partial_view_class' => 'sf',
));
