<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/11/09 12:23:35
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_partial_view_class' => 'sf',
));
