<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CitaComentario', 'doctrine');

/**
 * BaseCitaComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cita_comentario
 * @property integer $id_cita
 * @property string $comentario
 * @property date $fecha_comentario
 * @property Cita $Cita
 * 
 * @method integer        getIdCitaComentario()   Returns the current record's "id_cita_comentario" value
 * @method integer        getIdCita()             Returns the current record's "id_cita" value
 * @method string         getComentario()         Returns the current record's "comentario" value
 * @method date           getFechaComentario()    Returns the current record's "fecha_comentario" value
 * @method Cita           getCita()               Returns the current record's "Cita" value
 * @method CitaComentario setIdCitaComentario()   Sets the current record's "id_cita_comentario" value
 * @method CitaComentario setIdCita()             Sets the current record's "id_cita" value
 * @method CitaComentario setComentario()         Sets the current record's "comentario" value
 * @method CitaComentario setFechaComentario()    Sets the current record's "fecha_comentario" value
 * @method CitaComentario setCita()               Sets the current record's "Cita" value
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCitaComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cita_comentario');
        $this->hasColumn('id_cita_comentario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comentario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_comentario', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cita', array(
             'local' => 'id_cita',
             'foreign' => 'id_cita'));
    }
}