<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CalendarExcepcion', 'doctrine');

/**
 * BaseCalendarExcepcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_calendar_exception
 * @property time $inicio_excepcion
 * @property time $fin_excepcion
 * @property integer $status
 * @property date $fecha_excepcion
 * @property string $motivo_excepcion
 * 
 * @method integer           getIdCalendarException()   Returns the current record's "id_calendar_exception" value
 * @method time              getInicioExcepcion()       Returns the current record's "inicio_excepcion" value
 * @method time              getFinExcepcion()          Returns the current record's "fin_excepcion" value
 * @method integer           getStatus()                Returns the current record's "status" value
 * @method date              getFechaExcepcion()        Returns the current record's "fecha_excepcion" value
 * @method string            getMotivoExcepcion()       Returns the current record's "motivo_excepcion" value
 * @method CalendarExcepcion setIdCalendarException()   Sets the current record's "id_calendar_exception" value
 * @method CalendarExcepcion setInicioExcepcion()       Sets the current record's "inicio_excepcion" value
 * @method CalendarExcepcion setFinExcepcion()          Sets the current record's "fin_excepcion" value
 * @method CalendarExcepcion setStatus()                Sets the current record's "status" value
 * @method CalendarExcepcion setFechaExcepcion()        Sets the current record's "fecha_excepcion" value
 * @method CalendarExcepcion setMotivoExcepcion()       Sets the current record's "motivo_excepcion" value
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendarExcepcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('calendar_excepcion');
        $this->hasColumn('id_calendar_exception', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('inicio_excepcion', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fin_excepcion', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_excepcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('motivo_excepcion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}