<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rol', 'doctrine');

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_rol
 * @property string $nombre
 * @property integer $status
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getIdRol()   Returns the current record's "id_rol" value
 * @method string              getNombre()  Returns the current record's "nombre" value
 * @method integer             getStatus()  Returns the current record's "status" value
 * @method Doctrine_Collection getUsuario() Returns the current record's "Usuario" collection
 * @method Rol                 setIdRol()   Sets the current record's "id_rol" value
 * @method Rol                 setNombre()  Sets the current record's "nombre" value
 * @method Rol                 setStatus()  Sets the current record's "status" value
 * @method Rol                 setUsuario() Sets the current record's "Usuario" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id_rol', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'id_rol',
             'foreign' => 'id_rol'));
    }
}