<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Empleado', 'doctrine');

/**
 * BaseEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_empleado
 * @property integer $id_usuario
 * @property integer $id_posicion
 * @property integer $id_departamento
 * @property date $fecha_contratacion
 * @property Departamento $Departamento
 * @property Posicion $Posicion
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Cita
 * @property Doctrine_Collection $HorarioEmpleado
 * 
 * @method integer             getIdEmpleado()         Returns the current record's "id_empleado" value
 * @method integer             getIdUsuario()          Returns the current record's "id_usuario" value
 * @method integer             getIdPosicion()         Returns the current record's "id_posicion" value
 * @method integer             getIdDepartamento()     Returns the current record's "id_departamento" value
 * @method date                getFechaContratacion()  Returns the current record's "fecha_contratacion" value
 * @method Departamento        getDepartamento()       Returns the current record's "Departamento" value
 * @method Posicion            getPosicion()           Returns the current record's "Posicion" value
 * @method Usuario             getUsuario()            Returns the current record's "Usuario" value
 * @method Doctrine_Collection getCita()               Returns the current record's "Cita" collection
 * @method Doctrine_Collection getHorarioEmpleado()    Returns the current record's "HorarioEmpleado" collection
 * @method Empleado            setIdEmpleado()         Sets the current record's "id_empleado" value
 * @method Empleado            setIdUsuario()          Sets the current record's "id_usuario" value
 * @method Empleado            setIdPosicion()         Sets the current record's "id_posicion" value
 * @method Empleado            setIdDepartamento()     Sets the current record's "id_departamento" value
 * @method Empleado            setFechaContratacion()  Sets the current record's "fecha_contratacion" value
 * @method Empleado            setDepartamento()       Sets the current record's "Departamento" value
 * @method Empleado            setPosicion()           Sets the current record's "Posicion" value
 * @method Empleado            setUsuario()            Sets the current record's "Usuario" value
 * @method Empleado            setCita()               Sets the current record's "Cita" collection
 * @method Empleado            setHorarioEmpleado()    Sets the current record's "HorarioEmpleado" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleado');
        $this->hasColumn('id_empleado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_posicion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_departamento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_contratacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Departamento', array(
             'local' => 'id_departamento',
             'foreign' => 'id_departamento'));

        $this->hasOne('Posicion', array(
             'local' => 'id_posicion',
             'foreign' => 'id_posicion'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $this->hasMany('Cita', array(
             'local' => 'id_empleado',
             'foreign' => 'id_empleado'));

        $this->hasMany('HorarioEmpleado', array(
             'local' => 'id_empleado',
             'foreign' => 'id_empleado'));
    }
}