<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RecetaCita', 'doctrine');

/**
 * BaseRecetaCita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_receta_cita
 * @property integer $id_cita
 * @property integer $id_medicina
 * @property integer $cantidad
 * @property string $receta_indicacion
 * @property Cita $Cita
 * @property Medicina $Medicina
 * 
 * @method integer    getIdRecetaCita()      Returns the current record's "id_receta_cita" value
 * @method integer    getIdCita()            Returns the current record's "id_cita" value
 * @method integer    getIdMedicina()        Returns the current record's "id_medicina" value
 * @method integer    getCantidad()          Returns the current record's "cantidad" value
 * @method string     getRecetaIndicacion()  Returns the current record's "receta_indicacion" value
 * @method Cita       getCita()              Returns the current record's "Cita" value
 * @method Medicina   getMedicina()          Returns the current record's "Medicina" value
 * @method RecetaCita setIdRecetaCita()      Sets the current record's "id_receta_cita" value
 * @method RecetaCita setIdCita()            Sets the current record's "id_cita" value
 * @method RecetaCita setIdMedicina()        Sets the current record's "id_medicina" value
 * @method RecetaCita setCantidad()          Sets the current record's "cantidad" value
 * @method RecetaCita setRecetaIndicacion()  Sets the current record's "receta_indicacion" value
 * @method RecetaCita setCita()              Sets the current record's "Cita" value
 * @method RecetaCita setMedicina()          Sets the current record's "Medicina" value
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecetaCita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('receta_cita');
        $this->hasColumn('id_receta_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_medicina', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('receta_indicacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cita', array(
             'local' => 'id_cita',
             'foreign' => 'id_cita'));

        $this->hasOne('Medicina', array(
             'local' => 'id_medicina',
             'foreign' => 'id_medicina'));
    }
}