<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPresentacion', 'doctrine');

/**
 * BaseTipoPresentacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_presentacion
 * @property string $nombre
 * @property integer $status
 * @property Doctrine_Collection $Medicina
 * 
 * @method integer             getIdTipoPresentacion()   Returns the current record's "id_tipo_presentacion" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method integer             getStatus()               Returns the current record's "status" value
 * @method Doctrine_Collection getMedicina()             Returns the current record's "Medicina" collection
 * @method TipoPresentacion    setIdTipoPresentacion()   Sets the current record's "id_tipo_presentacion" value
 * @method TipoPresentacion    setNombre()               Sets the current record's "nombre" value
 * @method TipoPresentacion    setStatus()               Sets the current record's "status" value
 * @method TipoPresentacion    setMedicina()             Sets the current record's "Medicina" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoPresentacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_presentacion');
        $this->hasColumn('id_tipo_presentacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Medicina', array(
             'local' => 'id_tipo_presentacion',
             'foreign' => 'id_tipo_presentacion'));
    }
}