<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Posicion', 'doctrine');

/**
 * BasePosicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_posicion
 * @property string $nombre
 * @property integer $status
 * @property Doctrine_Collection $Empleado
 * 
 * @method integer             getIdPosicion()  Returns the current record's "id_posicion" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method integer             getStatus()      Returns the current record's "status" value
 * @method Doctrine_Collection getEmpleado()    Returns the current record's "Empleado" collection
 * @method Posicion            setIdPosicion()  Sets the current record's "id_posicion" value
 * @method Posicion            setNombre()      Sets the current record's "nombre" value
 * @method Posicion            setStatus()      Sets the current record's "status" value
 * @method Posicion            setEmpleado()    Sets the current record's "Empleado" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posicion');
        $this->hasColumn('id_posicion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empleado', array(
             'local' => 'id_posicion',
             'foreign' => 'id_posicion'));
    }
}