<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoCita', 'doctrine');

/**
 * BaseEstadoCita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_cita
 * @property string $nombre
 * @property integer $status
 * @property Doctrine_Collection $Cita
 * 
 * @method integer             getIdEstadoCita()   Returns the current record's "id_estado_cita" value
 * @method string              getNombre()         Returns the current record's "nombre" value
 * @method integer             getStatus()         Returns the current record's "status" value
 * @method Doctrine_Collection getCita()           Returns the current record's "Cita" collection
 * @method EstadoCita          setIdEstadoCita()   Sets the current record's "id_estado_cita" value
 * @method EstadoCita          setNombre()         Sets the current record's "nombre" value
 * @method EstadoCita          setStatus()         Sets the current record's "status" value
 * @method EstadoCita          setCita()           Sets the current record's "Cita" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoCita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_cita');
        $this->hasColumn('id_estado_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cita', array(
             'local' => 'id_estado_cita',
             'foreign' => 'id_estado_cita'));
    }
}