<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cita', 'doctrine');

/**
 * BaseCita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cita
 * @property integer $id_paciente
 * @property integer $id_empleado
 * @property date $fecha_cita
 * @property time $inicio_hora_cita
 * @property time $fin_hora_cita
 * @property integer $id_estado_cita
 * @property date $fecha_creacion
 * @property decimal $peso_pacientel
 * @property decimal $temperatura_paciente
 * @property decimal $presion_paciente
 * @property decimal $altura_paciente
 * @property Empleado $Empleado
 * @property EstadoCita $EstadoCita
 * @property Paciente $Paciente
 * @property Doctrine_Collection $CitaComentario
 * @property Doctrine_Collection $RecetaCita
 * @property Doctrine_Collection $CuotasCita
 * 
 * @method integer             getIdCita()               Returns the current record's "id_cita" value
 * @method integer             getIdPaciente()           Returns the current record's "id_paciente" value
 * @method integer             getIdEmpleado()           Returns the current record's "id_empleado" value
 * @method date                getFechaCita()            Returns the current record's "fecha_cita" value
 * @method time                getInicioHoraCita()       Returns the current record's "inicio_hora_cita" value
 * @method time                getFinHoraCita()          Returns the current record's "fin_hora_cita" value
 * @method integer             getIdEstadoCita()         Returns the current record's "id_estado_cita" value
 * @method date                getFechaCreacion()        Returns the current record's "fecha_creacion" value
 * @method decimal             getPesoPacientel()        Returns the current record's "peso_pacientel" value
 * @method decimal             getTemperaturaPaciente()  Returns the current record's "temperatura_paciente" value
 * @method decimal             getPresionPaciente()      Returns the current record's "presion_paciente" value
 * @method decimal             getAlturaPaciente()       Returns the current record's "altura_paciente" value
 * @method Empleado            getEmpleado()             Returns the current record's "Empleado" value
 * @method EstadoCita          getEstadoCita()           Returns the current record's "EstadoCita" value
 * @method Paciente            getPaciente()             Returns the current record's "Paciente" value
 * @method Doctrine_Collection getCitaComentario()       Returns the current record's "CitaComentario" collection
 * @method Doctrine_Collection getRecetaCita()           Returns the current record's "RecetaCita" collection
 * @method Doctrine_Collection getCuotasCita()           Returns the current record's "CuotasCita" collection
 * @method Cita                setIdCita()               Sets the current record's "id_cita" value
 * @method Cita                setIdPaciente()           Sets the current record's "id_paciente" value
 * @method Cita                setIdEmpleado()           Sets the current record's "id_empleado" value
 * @method Cita                setFechaCita()            Sets the current record's "fecha_cita" value
 * @method Cita                setInicioHoraCita()       Sets the current record's "inicio_hora_cita" value
 * @method Cita                setFinHoraCita()          Sets the current record's "fin_hora_cita" value
 * @method Cita                setIdEstadoCita()         Sets the current record's "id_estado_cita" value
 * @method Cita                setFechaCreacion()        Sets the current record's "fecha_creacion" value
 * @method Cita                setPesoPacientel()        Sets the current record's "peso_pacientel" value
 * @method Cita                setTemperaturaPaciente()  Sets the current record's "temperatura_paciente" value
 * @method Cita                setPresionPaciente()      Sets the current record's "presion_paciente" value
 * @method Cita                setAlturaPaciente()       Sets the current record's "altura_paciente" value
 * @method Cita                setEmpleado()             Sets the current record's "Empleado" value
 * @method Cita                setEstadoCita()           Sets the current record's "EstadoCita" value
 * @method Cita                setPaciente()             Sets the current record's "Paciente" value
 * @method Cita                setCitaComentario()       Sets the current record's "CitaComentario" collection
 * @method Cita                setRecetaCita()           Sets the current record's "RecetaCita" collection
 * @method Cita                setCuotasCita()           Sets the current record's "CuotasCita" collection
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cita');
        $this->hasColumn('id_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_paciente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_empleado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_cita', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('inicio_hora_cita', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fin_hora_cita', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_estado_cita', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('peso_pacientel', 'decimal', 5, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             'scale' => '2',
             ));
        $this->hasColumn('temperatura_paciente', 'decimal', 5, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             'scale' => '2',
             ));
        $this->hasColumn('presion_paciente', 'decimal', 5, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             'scale' => '2',
             ));
        $this->hasColumn('altura_paciente', 'decimal', 5, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empleado', array(
             'local' => 'id_empleado',
             'foreign' => 'id_empleado'));

        $this->hasOne('EstadoCita', array(
             'local' => 'id_estado_cita',
             'foreign' => 'id_estado_cita'));

        $this->hasOne('Paciente', array(
             'local' => 'id_paciente',
             'foreign' => 'id_paciente'));

        $this->hasMany('CitaComentario', array(
             'local' => 'id_cita',
             'foreign' => 'id_cita'));

        $this->hasMany('RecetaCita', array(
             'local' => 'id_cita',
             'foreign' => 'id_cita'));

        $this->hasMany('CuotasCita', array(
             'local' => 'id_cita',
             'foreign' => 'id_cita'));
    }
}