<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PacienteTelefono', 'doctrine');

/**
 * BasePacienteTelefono
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_paciente_telefono
 * @property string $telefono
 * @property integer $status
 * @property integer $paciente_id
 * @property Paciente $Paciente
 * 
 * @method integer          getIdPacienteTelefono()   Returns the current record's "id_paciente_telefono" value
 * @method string           getTelefono()             Returns the current record's "telefono" value
 * @method integer          getStatus()               Returns the current record's "status" value
 * @method integer          getPacienteId()           Returns the current record's "paciente_id" value
 * @method Paciente         getPaciente()             Returns the current record's "Paciente" value
 * @method PacienteTelefono setIdPacienteTelefono()   Sets the current record's "id_paciente_telefono" value
 * @method PacienteTelefono setTelefono()             Sets the current record's "telefono" value
 * @method PacienteTelefono setStatus()               Sets the current record's "status" value
 * @method PacienteTelefono setPacienteId()           Sets the current record's "paciente_id" value
 * @method PacienteTelefono setPaciente()             Sets the current record's "Paciente" value
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePacienteTelefono extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente_telefono');
        $this->hasColumn('id_paciente_telefono', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('paciente_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'paciente_id',
             'foreign' => 'id_paciente'));
    }
}