# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sistema de Control de Clinica
    description:  Sistema desarrollado para la materia de ASI2 UFG. 2014.
    keywords:     symfony, clinic, project
    language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, plugins/metisMenu/metisMenu.min.css, plugins/timeline.css, sb-admin-2.css, plugins/morris.css, font-awesome-4.1.0/css/font-awesome.min.css, jquery-ui.css, jquery.gritter.css, jquery.dataTables.css, dataTables.bootstrap.css]

  javascripts:    [jquery-1.11.0.js, bootstrap.min.js, plugins/metisMenu/metisMenu.min.js, sb-admin-2.js, jsUtils.js, jquery-ui.js, jquery.gritter.js, jquery.dataTables.min.js, dataTables.bootstrap.js]

  has_layout:     true
  layout:         layout
