<?php

/**
 * CasaMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CasaMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CasaMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CasaMedica');
    }
}