<?php

/**
 * CitaComentarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitaComentarioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CitaComentarioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('CitaComentario');
    }

    public function getCommentByPacient($iPacienteId) {
        $oDQL = $this->createQuery("cc")
                ->where("cc.id_cita IN (SELECT c.id_cita FROM Cita c Where c.id_paciente = ?)", $iPacienteId)
                ->orderBy("cc.fecha_comentario DESC");
        return $oDQL->execute();
    }

}