<?php

/**
 * Cita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cita extends BaseCita {

    public function __toString() {
        return $this->getPaciente() . " :: " . $this->getInicioHoraCita();
    }

}