<?php

/**
 * CuotasCitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuotasCitaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuotasCitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CuotasCita');
    }
}