<?php

/**
 * EstadoCitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoCitaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoCitaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoCita');
    }
}