<?php

/**
 * HorarioEmpleadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorarioEmpleadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorarioEmpleadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorarioEmpleado');
    }
}