<?php

/**
 * MedicinaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicinaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicinaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicina');
    }
}