<?php

/**
 * PacienteTelefono
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PacienteTelefono extends BasePacienteTelefono {

    public function __toString() {
        return $this->getTelefono();
    }

    public function getId() {
        return $this->getIdPacienteTelefono();
    }

}
