<?php

/**
 * PosicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PosicionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PosicionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Posicion');
    }
}