<?php

/**
 * RecetaCitaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecetaCitaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object RecetaCitaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('RecetaCita');
    }

    public function getMedByPatient($iPaciente) {
        # SELECT * FROM receta_cita rc Where rc.id_cita IN (SELECT c.id_cita FROM cita c Where c.id_paciente = 1);
        $oDQL = $this->createQuery("rc")
                ->where("rc.id_cita IN (SELECT c.id_cita FROM Cita c Where c.id_paciente = ?)", array($iPaciente));
        return $oDQL->execute();
    }

    public function getJsonBarChart($iPaciente) {
        $oDQL = $this->createQuery("rc")
                ->select("rc.id_medicina as id_medicina, sum(rc.cantidad) as cantidad")
                ->where("rc.id_cita IN (SELECT c.id_cita FROM Cita c WHERE c.id_paciente = {$iPaciente})")
                ->groupBy("rc.id_medicina");
        $aResultset = $oDQL->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        $oDQLMedicine = Doctrine_Query::create()
                ->select("m.id_medicina, m.nombre")
                ->from("Medicina m");
        $aMedicineList = $oDQLMedicine->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        $aFinal = array();
        foreach ($aResultset as $aRecord) {
            foreach ($aMedicineList as $aMedicineRecord) {
                if ($aRecord['id_medicina'] == $aMedicineRecord['id_medicina']) {
                    $aRecord['medicina_name'] = $aMedicineRecord['nombre'];
                    array_push($aFinal, array($aMedicineRecord['nombre'], (int) $aRecord['cantidad']));
                }
            }
        }
        return $aFinal;
    }

    public function getRecetasDespacho() {
        $aData = array();
        $oDQL = $this->createQuery("rc");
        $oRecetaCitaRecordList = $oDQL->execute();
        $oRecetaCitaRecord = new RecetaCita();
        foreach ($oRecetaCitaRecordList as $oRecetaCitaRecord) {
            if ($oRecetaCitaRecord->getCita()->getIdEstadoCita() == 5) {
                array_push($aData, $oRecetaCitaRecord);
            }
        }
        return $aData;
    }

}