<?php

/**
 * Rol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asi2vSymfony
 * @subpackage model
 * @author     McCubo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rol extends BaseRol {

    public function __toString() {
        return $this->getNombre();
    }

    public function isRolActive() {
        $iStatus = intval($this->getStatus());
        return $iStatus == 1;
    }

}
