CalendarExcepcion:
  connection: doctrine
  tableName: calendar_excepcion
  columns:
    id_calendar_exception:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    inicio_excepcion:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fin_excepcion:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
    fecha_excepcion:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    motivo_excepcion:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
CasaMedica:
  connection: doctrine
  tableName: casa_medica
  columns:
    id_casa_medica:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre_contacto:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefono:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_contrato:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
  relations:
    Medicina:
      local: id_casa_medica
      foreign: id_casa_medica
      type: many
Cita:
  connection: doctrine
  tableName: cita
  columns:
    id_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_paciente:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_empleado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_cita:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inicio_hora_cita:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fin_hora_cita:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_estado_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_creacion:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    peso_pacientel:
      type: 'decimal(5, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    temperatura_paciente:
      type: 'decimal(5, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    presion_paciente:
      type: 'decimal(5, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    altura_paciente:
      type: 'decimal(5, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Empleado:
      local: id_empleado
      foreign: id_empleado
      type: one
    EstadoCita:
      local: id_estado_cita
      foreign: id_estado_cita
      type: one
    Paciente:
      local: id_paciente
      foreign: id_paciente
      type: one
    CitaComentario:
      local: id_cita
      foreign: id_cita
      type: many
    RecetaCita:
      local: id_cita
      foreign: id_cita
      type: many
CitaComentario:
  connection: doctrine
  tableName: cita_comentario
  columns:
    id_cita_comentario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    comentario:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_comentario:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Cita:
      local: id_cita
      foreign: id_cita
      type: one
CuotasCita:
  connection: doctrine
  tableName: cuotas_cita
  columns:
    id_cuotas_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    monto_donacion:
      type: 'decimal(6, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
  relations:
    Cita:
      local: id_cita
      foreign: id_cita
      type: one
Departamento:
  connection: doctrine
  tableName: departamento
  columns:
    id_departamento:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Empleado:
      local: id_departamento
      foreign: id_departamento
      type: many
Empleado:
  connection: doctrine
  tableName: empleado
  columns:
    id_empleado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_posicion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_departamento:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_contratacion:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Departamento:
      local: id_departamento
      foreign: id_departamento
      type: one
    Posicion:
      local: id_posicion
      foreign: id_posicion
      type: one
    Usuario:
      local: id_usuario
      foreign: id_usuario
      type: one
    Cita:
      local: id_empleado
      foreign: id_empleado
      type: many
#    HorarioEmpleado:
#      local: id_empleado
#      foreign: id_empleado
#      type: many
EstadoCita:
  connection: doctrine
  tableName: estado_cita
  columns:
    id_estado_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Cita:
      local: id_estado_cita
      foreign: id_estado_cita
      type: many
HorarioEmpleado:
  connection: doctrine
  tableName: horario_empleado
  columns:
    id_horario_empleado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_empleado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    hora_inicio:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    hora_fin:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    dia_horario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Empleado:
      local: id_empleado
      foreign: id_empleado
      type: one
Medicina:
  connection: doctrine
  tableName: medicina
  columns:
    id_medicina:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo_presentacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_casa_medica:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    limite_menor:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    limite_normal:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    limite_optimo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    precio_unidad:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    existencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
  relations:
    CasaMedica:
      local: id_casa_medica
      foreign: id_casa_medica
      type: one
    TipoPresentacion:
      local: id_tipo_presentacion
      foreign: id_tipo_presentacion
      type: one
    RecetaCita:
      local: id_medicina
      foreign: id_medicina
      type: many
Paciente:
  connection: doctrine
  tableName: paciente
  columns:
    id_paciente:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    tipo_sanguineo:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_nacimiento:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Usuario:
      local: id_usuario
      foreign: id_usuario
      type: one
    Cita:
      local: id_paciente
      foreign: id_paciente
      type: many
Posicion:
  connection: doctrine
  tableName: posicion
  columns:
    id_posicion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
  relations:
    Empleado:
      local: id_posicion
      foreign: id_posicion
      type: many
RecetaCita:
  connection: doctrine
  tableName: receta_cita
  columns:
    id_receta_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_cita:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_medicina:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    cantidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
    receta_indicacion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Cita:
      local: id_cita
      foreign: id_cita
      type: one
    Medicina:
      local: id_medicina
      foreign: id_medicina
      type: one
Rol:
  connection: doctrine
  tableName: rol
  columns:
    id_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
  relations:
    Usuario:
      local: id_rol
      foreign: id_rol
      type: many
TipoPresentacion:
  connection: doctrine
  tableName: tipo_presentacion
  columns:
    id_tipo_presentacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
  relations:
    Medicina:
      local: id_tipo_presentacion
      foreign: id_tipo_presentacion
      type: many
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    username:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    apellido:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    genero:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ultimo_ingreso:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
  relations:
    Rol:
      local: id_rol
      foreign: id_rol
      type: one
    Empleado:
      local: id_usuario
      foreign: id_usuario
      type: many
    Paciente:
      local: id_usuario
      foreign: id_usuario
      type: many
