# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sistema de Control de Clinica - Error
    description:  Sistema desarrollado para la materia de ASI2 UFG. 2014.
    keywords:     symfony, clinic, project
    language:     en
    #robots:       index, follow

  stylesheets:    [error.css]

  javascripts:    []

  has_layout:     true
  layout:         error_layout