<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/09/01 07:08:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=db_nazareth_clinic',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
