<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/09/01 07:08:12
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_partial_view_class' => 'sf',
));
